import './globals.css'
import Footer from '@/components/footer/Footer'
import NavBar from '@/components/navBar/NavBar'
import { Inter } from 'next/font/google'
import {ThemeProvider} from '@/ThemeContext/ThemeContext'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className }>
        <ThemeProvider>
        <div className='container'>
          <div className='wrapper'>

            <NavBar />
            <div className='flex justify-center '>

            {children}
            </div>

            {/* <Footer /> */}



          </div>


        </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
